/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.ticket;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import static java.sql.Types.NULL;
import java.util.Arrays;
import java.util.Timer;
import javax.swing.JOptionPane;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class BLogin extends javax.swing.JFrame {

    String email, password, conpassword, mobile;

    /**
     * Creates new form Login
     */
    public BLogin() {
        initComponents();
    }

    class CloseDialogTask extends TimerTask {

        public void run() {
            jFrame1.setVisible(false);
            BLogin.this.setVisible(false);
            new DNewhome(email).setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_Ok = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jFrame3 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField_newPassword = new javax.swing.JPasswordField();
        jPasswordField_conPassword = new javax.swing.JPasswordField();
        jButton_Ok1 = new javax.swing.JButton();
        Login = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        Pswd = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLogin = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();
        jSignup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jForgotpswd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_logo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(247, 131));
        jFrame1.setResizable(false);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/LZY3.gif"))); // NOI18N

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, Short.MAX_VALUE)
        );

        jLabel3.setText("Email ID");

        jLabel6.setText("Mobile");

        jButton_Ok.setText("OK");
        jButton_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Ok)
                .addGap(134, 134, 134))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Ok)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setText("New Password ");

        jLabel2.setText("Confirm Password ");

        jButton_Ok1.setText("OK");
        jButton_Ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Ok1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))
                        .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPasswordField_newPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jPasswordField_conPassword)))
                    .addGroup(jFrame3Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton_Ok1)))
                .addGap(50, 50, 50))
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordField_newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField_conPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Ok1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 20, 860, 800));
        setMinimumSize(new java.awt.Dimension(860, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(860, 800));
        getContentPane().setLayout(null);

        Login.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        Login.setForeground(new java.awt.Color(240, 240, 240));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Login");
        getContentPane().add(Login);
        Login.setBounds(0, 250, 860, 53);

        UserName.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        UserName.setForeground(new java.awt.Color(240, 240, 240));
        UserName.setText("Email ID    :");
        getContentPane().add(UserName);
        UserName.setBounds(280, 330, 110, 29);

        Pswd.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        Pswd.setForeground(new java.awt.Color(240, 240, 240));
        Pswd.setText("Password   :");
        getContentPane().add(Pswd);
        Pswd.setBounds(280, 370, 101, 29);

        jTextField_username.setPreferredSize(new java.awt.Dimension(8, 20));
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_username);
        jTextField_username.setBounds(410, 330, 180, 30);

        jPasswordField_password.setPreferredSize(new java.awt.Dimension(8, 20));
        getContentPane().add(jPasswordField_password);
        jPasswordField_password.setBounds(410, 370, 180, 30);

        jLogin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLogin.setText("Login");
        jLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jLogin);
        jLogin.setBounds(320, 430, 90, 34);

        jCancel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCancel.setText("Cancel");
        jCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jCancel);
        jCancel.setBounds(450, 430, 90, 34);

        jSignup.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jSignup.setForeground(new java.awt.Color(0, 102, 255));
        jSignup.setText("Sign up");
        jSignup.setBorder(null);
        jSignup.setBorderPainted(false);
        jSignup.setContentAreaFilled(false);
        jSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSignupActionPerformed(evt);
            }
        });
        getContentPane().add(jSignup);
        jSignup.setBounds(420, 510, 70, 40);

        jLabel5.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("To register");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 510, 100, 40);

        jForgotpswd.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jForgotpswd.setForeground(new java.awt.Color(204, 204, 204));
        jForgotpswd.setText("Forgot Password");
        jForgotpswd.setContentAreaFilled(false);
        jForgotpswd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jForgotpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jForgotpswdActionPerformed(evt);
            }
        });
        getContentPane().add(jForgotpswd);
        jForgotpswd.setBounds(370, 540, 140, 27);

        jLabel4.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("here.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 510, 60, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 150, 860, 10);

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie/ticket/logo-edit.png"))); // NOI18N
        getContentPane().add(jLabel_logo);
        jLabel_logo.setBounds(70, 0, 190, 150);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/spi-bg.jpg"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(860, 800));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 860, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // Login 
        email = jTextField_username.getText();
        password = String.valueOf(jPasswordField_password.getPassword());
        if (email.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, " Please enter username/password. ");
        } else {
            Connection con = null;

            CallableStatement cs;
            String columnValue = "";
            String pwd = "nill";
            try {

                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
                cs = con.prepareCall("{CALL getSignup_pro(?)}");
                cs.setString(1, jTextField_username.getText());
                ResultSet rs = cs.executeQuery();
                ResultSetMetaData rsmd = rs.getMetaData();
                int columnsNumber = rsmd.getColumnCount();

                while (rs.next()) {
                    for (int i = 1; i <= columnsNumber; i++) {
                        if (i > 1) {
                            System.out.print(",  ");
                        }
                        columnValue = rs.getString(i);
                        //System.out.print(columnValue);
                    }
                    //System.out.println("");
                }

                if (columnValue != "null") {
                    String[] values = columnValue.split(";");
                    pwd = values[2];
                    //System.out.println(pwd);
                }
                if (password.equals(pwd)) {
                    System.out.println(email);
                    jFrame1.setVisible(true);
                    jFrame1.setLocationRelativeTo(this);
                    jFrame1.pack();

                    int timeout_ms = 4000;
                    Timer timer = new Timer();
                    timer.schedule(new CloseDialogTask(), timeout_ms);
                } else {
                    JOptionPane.showMessageDialog(this, "Username or Password Incorrect. Please try again.");
                    jTextField_username.setText("");
                    jPasswordField_password.setText("");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_jLoginActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        // Cancel - Return to Homepage
        this.setVisible(false);
        new A_Home().setVisible(true);
    }//GEN-LAST:event_jCancelActionPerformed

    private void jSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSignupActionPerformed
        //Click to Sign up
        new CSignup().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jSignupActionPerformed

    private void jForgotpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jForgotpswdActionPerformed
        // TODO add your handling code here:
        jFrame2.setVisible(true);
        jFrame2.pack();
        jFrame2.setLocationRelativeTo(this);
    }//GEN-LAST:event_jForgotpswdActionPerformed

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jButton_Ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Ok1ActionPerformed
        // TODO add your handling code here:
        if (jPasswordField_newPassword.equals("") || jPasswordField_conPassword.equals("")) {
            JOptionPane.showMessageDialog(this, " Please enter password. ");
        } else {
            Connection con = null;
            CallableStatement cs;

            try {

                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
                cs = con.prepareCall("{CALL getSignup_pro(?,?)}");
                cs.setString(1, email);
                password = String.valueOf(jPasswordField_newPassword.getPassword());
                conpassword = String.valueOf(jPasswordField_conPassword.getPassword());
                cs.setString(2, password);
                if (password.equals(conpassword)) {
                    cs.execute();
                    JOptionPane.showMessageDialog(this, "Password has been changed successfully.");
                    jFrame3.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Passwords do not match.Try again.");
                    jPasswordField_newPassword.setText("");
                    jPasswordField_conPassword.setText("");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton_Ok1ActionPerformed

    private void jButton_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OkActionPerformed
        // TODO add your handling code here:
        email = jTextField1.getText();
        mobile = jTextField2.getText();

        Connection con = null;
        CallableStatement cs;
        String columnValue = "";
        String pwd = "nill";
        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
            cs = con.prepareCall("{CALL getSignup_pro(?)}");
            cs.setString(1, email);
            ResultSet rs = cs.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnsNumber = rsmd.getColumnCount();

            while (rs.next()) {
                for (int i = 1; i <= columnsNumber; i++) {
                    if (i > 1) {
                        System.out.print(",  ");
                    }
                    columnValue = rs.getString(i);
                    System.out.print(columnValue);
                }
                System.out.println("");
            }
            if (columnValue != "null") {
                String[] values = columnValue.split(";");
                pwd = values[3];
                System.out.println(pwd);
            }

            if (mobile.equals(pwd)) {
                jFrame2.setVisible(false);
                jFrame3.setVisible(true);
                jFrame3.pack();
                jFrame3.setLocationRelativeTo(this);
            } else {
                JOptionPane.showMessageDialog(this, "Mobile Number Mismatched. Can't reset password.");
                jTextField1.setText("");
                jTextField2.setText("");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Invalid Credentials");
        }

    }//GEN-LAST:event_jButton_OkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Pswd;
    private javax.swing.JLabel UserName;
    private javax.swing.JButton jButton_Ok;
    private javax.swing.JButton jButton_Ok1;
    private javax.swing.JButton jCancel;
    private javax.swing.JButton jForgotpswd;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JButton jLogin;
    private javax.swing.JPasswordField jPasswordField_conPassword;
    private javax.swing.JPasswordField jPasswordField_newPassword;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jSignup;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
