/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.ticket;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CSignup extends javax.swing.JFrame {

    String email;

    /**
     * Creates new form CSignup
     */
    public CSignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_signup = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_address1 = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_mobileno = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jLabel_rePassword = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jTextField_address1 = new javax.swing.JTextField();
        jTextField_address2 = new javax.swing.JTextField();
        jTextField_mobileno = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jLabel_address2 = new javax.swing.JLabel();
        jSignup = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();
        jPasswordField_password = new javax.swing.JPasswordField();
        jPasswordField_repassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_logo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 20, 860, 800));
        setMinimumSize(new java.awt.Dimension(860, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(860, 800));
        getContentPane().setLayout(null);

        jLabel_signup.setFont(new java.awt.Font("TimeScrDLig", 1, 21)); // NOI18N
        jLabel_signup.setForeground(new java.awt.Color(245, 242, 242));
        jLabel_signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_signup.setText("Sign up");
        getContentPane().add(jLabel_signup);
        jLabel_signup.setBounds(370, 190, 133, 53);

        jLabel_name.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name.setText("Name :");
        getContentPane().add(jLabel_name);
        jLabel_name.setBounds(210, 280, 250, 30);

        jLabel_address1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel_address1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_address1.setText("Address (Line 1) :");
        getContentPane().add(jLabel_address1);
        jLabel_address1.setBounds(210, 320, 250, 30);

        jLabel_email.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel_email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_email.setText("Email Id :");
        getContentPane().add(jLabel_email);
        jLabel_email.setBounds(210, 440, 250, 30);

        jLabel_mobileno.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel_mobileno.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_mobileno.setText("Mobile no. :");
        getContentPane().add(jLabel_mobileno);
        jLabel_mobileno.setBounds(210, 400, 250, 30);

        jLabel_password.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_password.setText("Password :");
        getContentPane().add(jLabel_password);
        jLabel_password.setBounds(210, 480, 250, 30);

        jLabel_rePassword.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel_rePassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_rePassword.setText("Re-enter Password :");
        getContentPane().add(jLabel_rePassword);
        jLabel_rePassword.setBounds(210, 520, 250, 30);

        jTextField_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_name.setPreferredSize(new java.awt.Dimension(8, 20));
        getContentPane().add(jTextField_name);
        jTextField_name.setBounds(436, 280, 180, 30);

        jTextField_address1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_address1.setPreferredSize(new java.awt.Dimension(8, 20));
        getContentPane().add(jTextField_address1);
        jTextField_address1.setBounds(436, 320, 180, 30);

        jTextField_address2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_address2.setPreferredSize(new java.awt.Dimension(8, 20));
        getContentPane().add(jTextField_address2);
        jTextField_address2.setBounds(436, 360, 180, 30);

        jTextField_mobileno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_mobileno.setPreferredSize(new java.awt.Dimension(8, 20));
        getContentPane().add(jTextField_mobileno);
        jTextField_mobileno.setBounds(436, 400, 180, 30);

        jTextField_email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_email.setPreferredSize(new java.awt.Dimension(8, 20));
        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_email);
        jTextField_email.setBounds(436, 440, 180, 30);

        jLabel_address2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel_address2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_address2.setText("Address (Line 2-Optional) :");
        getContentPane().add(jLabel_address2);
        jLabel_address2.setBounds(210, 360, 250, 30);

        jSignup.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jSignup.setText("Sign Up");
        jSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSignupActionPerformed(evt);
            }
        });
        getContentPane().add(jSignup);
        jSignup.setBounds(320, 590, 90, 34);

        jCancel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCancel.setText("Cancel");
        jCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jCancel);
        jCancel.setBounds(440, 590, 90, 34);

        jPasswordField_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField_password.setPreferredSize(new java.awt.Dimension(8, 20));
        getContentPane().add(jPasswordField_password);
        jPasswordField_password.setBounds(436, 480, 180, 30);

        jPasswordField_repassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField_repassword.setPreferredSize(new java.awt.Dimension(8, 20));
        getContentPane().add(jPasswordField_repassword);
        jPasswordField_repassword.setBounds(436, 520, 180, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 150, 860, 10);

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/logo-edit.png"))); // NOI18N
        getContentPane().add(jLabel_logo);
        jLabel_logo.setBounds(70, 0, 190, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/spi-bg.jpg"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -20, 860, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSignupActionPerformed
        // TODO add your handling code here:
        String name = jTextField_name.getText();
        String address = jTextField_address1.getText() + " " + jTextField_address2.getText();
        String mobile = jTextField_mobileno.getText();
        email = jTextField_email.getText();
        String password = String.valueOf(jPasswordField_password.getPassword());
        String confirmpassword = String.valueOf(jPasswordField_repassword.getPassword());
        if (name.equals("") || address.equals("") || email.equals("") || mobile.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, " Please enter all the details ");
        } else if (password.equals(confirmpassword)) 
        {
            Connection con = null;
            CallableStatement cs;
            
            try {
                Class.forName("java.sql.DriverManager");
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
                cs = con.prepareCall("{CALL insSignup(?,?,?,?,?)}");
                cs.setString(1,name);
                cs.setString(2,address);
                cs.setString(3,email);
                cs.setString(4,mobile);
                cs.setString(5,password);
                ResultSet rs = cs.executeQuery();
                /*Statement stmt = (Statement) con.createStatement();
                String query = "Insert into signup values('" + name + "','" + address + "','" + email + "','" + mobile + "','" + password + "');";
                stmt.executeUpdate(query);
                */
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            jTextField_name.setText("");
            jTextField_address1.setText("");
            jTextField_address2.setText("");
            jTextField_mobileno.setText("");
            jTextField_email.setText("");
            jPasswordField_password.setText("");
            jPasswordField_repassword.setText("");
            JOptionPane.showMessageDialog(this, "Signed up successfully.\n Proceed For Login.");
            this.setVisible(false);
            new BLogin().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Passwords do not match. Please re-enter correct password.");
        }
    }//GEN-LAST:event_jSignupActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BLogin().setVisible(true);
    }//GEN-LAST:event_jCancelActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel_address1;
    private javax.swing.JLabel jLabel_address2;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_mobileno;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_rePassword;
    private javax.swing.JLabel jLabel_signup;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JPasswordField jPasswordField_repassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jSignup;
    private javax.swing.JTextField jTextField_address1;
    private javax.swing.JTextField jTextField_address2;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_mobileno;
    private javax.swing.JTextField jTextField_name;
    // End of variables declaration//GEN-END:variables
}
