/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.ticket;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.imageio.ImageIO;
import java.sql.*;

/**
 *
 * @author User
 */
public class DNewhome extends javax.swing.JFrame {

    String email;

    /**
     * Creates new form DNewhome
     */
    public DNewhome() {
        initComponents();
    }

    public DNewhome(String mail) {
        email = mail;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel_cinema = new javax.swing.JLabel();
        jLogout = new javax.swing.JButton();
        jLabel_logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jPanel_running = new javax.swing.JPanel();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
            Statement stmt2= (Statement) con.createStatement();
            String query2="Select movieid,moviename,image from movie order by movieid desc;";
            ResultSet rs2= (ResultSet) stmt2.executeQuery(query2);

            while(rs2.next())
            {
                String moviename=rs2.getString("moviename");
                String image=rs2.getString("image");
                int movieid =rs2.getInt("movieid");
                System.out.println(moviename + " "+image +" "+movieid+" ");
                JButton b=new JButton();
                //last 3 not coming System.out.println(image);
                System.out.println(getClass().getResource("/pictures/"+image));
                Image img = ImageIO.read(getClass().getResource("/pictures/"+image));
                b.setIcon(new ImageIcon(img));
                b.setText(moviename);
                b.setContentAreaFilled(false);
                b.setForeground(Color.LIGHT_GRAY);
                b.setFont(Font.decode("Tunga-bold-18"));
                b.setSize(200,200);
                b.setCursor(new Cursor(Cursor.HAND_CURSOR));
                b.setHorizontalTextPosition(JButton.CENTER);
                b.setVerticalTextPosition(JButton.BOTTOM);
                b.addActionListener(new Action(movieid));
                jPanel_running.add(b);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        jLabel_nowrunning = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 20, 860, 800));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(860, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(860, 800));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 150, 860, 2);

        jLabel_cinema.setFont(new java.awt.Font("Lithos Pro Regular", 0, 24)); // NOI18N
        jLabel_cinema.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cinema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cinema.setText("Cinema");
        getContentPane().add(jLabel_cinema);
        jLabel_cinema.setBounds(370, 150, 118, 32);

        jLogout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLogout.setText("Log Out");
        jLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLogout.setBorderPainted(false);
        jLogout.setContentAreaFilled(false);
        jLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jLogout);
        jLogout.setBounds(780, 0, 80, 34);

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/logo-edit.png"))); // NOI18N
        getContentPane().add(jLabel_logo);
        jLabel_logo.setBounds(80, 0, 180, 150);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setVerifyInputWhenFocusTarget(false);

        jPanel_running.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_running.setOpaque(false);
        jPanel_running.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(jPanel_running);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 210, 860, 430);

        jLabel_nowrunning.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel_nowrunning.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_nowrunning.setText("Now Running");
        getContentPane().add(jLabel_nowrunning);
        jLabel_nowrunning.setBounds(380, 180, 110, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/spi-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -40, 862, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
        new A_Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DNewhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DNewhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DNewhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DNewhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DNewhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_cinema;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_nowrunning;
    private javax.swing.JButton jLogout;
    private javax.swing.JPanel jPanel_running;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    class Action implements ActionListener {

        int movie_id;

        Action(int i) {
            movie_id = i;
        }

        public void actionPerformed(ActionEvent e) {
            new E_movied(movie_id, email).setVisible(true);
            DNewhome.this.setVisible(false);
        }
    }
}
