/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.ticket;

import javax.swing.*;
import javax.swing.JInternalFrame;
import java.sql.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;



/**
 *
 * @author User
 */
public class F_shows extends javax.swing.JFrame {
    int theatre_id,ticket_count,movie_id;
    String name,movie_name,email,Date;
    Date date;
    /**
     * Creates new form E_fun
     */
    public F_shows(){
        initComponents(); 
    }
    
    public F_shows(Date d, int tc, int mid,String mname,String mail) {
        movie_id=mid;
        date=d;
        DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
        Date=df.format(d);
        ticket_count=tc;
        movie_name=mname;
        email=mail;
        
        
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel_showTiming = new javax.swing.JLabel();
        jBackhome = new javax.swing.JButton();
        jLogout = new javax.swing.JButton();
        jLabel_logo = new javax.swing.JLabel();
        jPanel_showTiming = new javax.swing.JPanel();
        try{
            System.out.println(" DATE: "+Date+" ");
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
            Statement stmt= (Statement) con.createStatement();
            String query="Select distinct theatreid from timing where movieid='"+movie_id+"' and '"+Date+"' between startdate and enddate;";

            ResultSet rs= (ResultSet) stmt.executeQuery(query);

            if(rs.next()){
                rs.beforeFirst();
            }
            else{
                JPanel jp = new JPanel();
                JLabel jl= new JLabel("No shows available.");
                jp.setOpaque(false);
                jl.setFont(Font.decode("Century Gothic-18"));
                jl.setForeground(Color.WHITE);
                jp.add(jl);
                jPanel_showTiming.add(jp);
            }

            while(rs.next()){
                int theatre_id=rs.getInt("theatreid");
                CallableStatement cs;
                String columnValue="";
                String name = "nill";
                try{

                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
                    /*
                    cs = con.prepareCall("{CALL getFshows_pro(?)}");
                    cs.setInt(1,theatre_id);
                    ResultSet rs1 = cs.executeQuery();
                    ResultSetMetaData rsmd = rs1.getMetaData();
                    int columnsNumber = rsmd.getColumnCount();
                    System.out.println("IN the cursor");
                    while (rs1.next())
                    {
                        for (int i = 1; i <= columnsNumber; i++) {
                            if (i > 1)
                            System.out.print(",  ");
                            columnValue = rs1.getString(i);
                            System.out.print(columnValue);
                        }
                        System.out.println("");
                    }
                    if(columnValue != "null"){
                        String[] values = columnValue.split(";");
                        name= values[0];
                        System.out.println("++"+name);
                    }
                    */

                    Statement stmt1= (Statement) con.createStatement();
                    String query1="Select timingid,starttime,enddate from timing where movieid='"+movie_id+"' and theatreid='"+theatre_id+"';";
                    ResultSet rs1= (ResultSet) stmt1.executeQuery(query1);

                    Statement stmt2= (Statement) con.createStatement();
                    String query2="Select Name from theatre where theatreid='"+theatre_id+"';";
                    ResultSet rs2= (ResultSet) stmt2.executeQuery(query2);
                    if(rs2.next()){
                        name=rs2.getString("Name");
                    }
                    System.out.println(" Rename: "+name);
                    if(name.length()<30){
                        for(int z=name.length();z<30;z++){
                            name+=" ";
                        }
                    }

                    JPanel jp1 = new JPanel();
                    JButton b1=new JButton(name);
                    jp1.setLayout(new BoxLayout(jp1, BoxLayout.X_AXIS));
                    b1.setAlignmentX(JButton.LEFT_ALIGNMENT);
                    b1.setContentAreaFilled(false);
                    b1.setFont(Font.decode("Century Gothic-18"));
                    b1.setForeground(Color.WHITE);
                    b1.addActionListener(new Action(theatre_id));
                    b1.setToolTipText("Click theatre name for theatre details.");
                    jp1.add(b1);

                    while(rs1.next())
                    {
                        String start_time=rs1.getString("starttime");
                        int timing_id=rs1.getInt("timingid");
                        Date d=rs1.getDate("enddate");
                        if(date.before(d)){
                            JButton time=new JButton(start_time);
                            time.setAlignmentX(JButton.LEFT_ALIGNMENT);
                            time.setFont(Font.decode("Century Gothic-15"));
                            time.setCursor(new Cursor(Cursor.HAND_CURSOR));
                            time.addActionListener(new Action1(start_time,theatre_id,timing_id));
                            jp1.add(time);
                        }
                    }

                    jp1.setAlignmentX(JPanel.LEFT_ALIGNMENT);
                    jp1.setOpaque(false);
                    jPanel_showTiming.add(jp1);
                    JPanel jp2=new JPanel();
                    jp2.setOpaque(false);
                    jPanel_showTiming.add(jp2);

                }
                catch(Exception e1){
                    e1.printStackTrace();
                }
            }
            System.out.println(" END of CUS CODE _end");
        }
        catch(Exception e){
            e.printStackTrace();
        }
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 20, 860, 800));
        setMinimumSize(new java.awt.Dimension(860, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(860, 800));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 147, 861, 10);

        jLabel_showTiming.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel_showTiming.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_showTiming.setText("Show Timings");
        getContentPane().add(jLabel_showTiming);
        jLabel_showTiming.setBounds(350, 170, 170, 32);

        jBackhome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBackhome.setForeground(new java.awt.Color(240, 240, 240));
        jBackhome.setText("Back to Home");
        jBackhome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        jBackhome.setContentAreaFilled(false);
        jBackhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBackhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackhomeActionPerformed(evt);
            }
        });
        getContentPane().add(jBackhome);
        jBackhome.setBounds(710, 600, 110, 34);

        jLogout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLogout.setText("Log Out");
        jLogout.setBorderPainted(false);
        jLogout.setContentAreaFilled(false);
        jLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLogout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jLogout);
        jLogout.setBounds(770, 0, 90, 34);

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/logo-edit.png"))); // NOI18N
        getContentPane().add(jLabel_logo);
        jLabel_logo.setBounds(80, 0, 180, 150);

        jPanel_showTiming.setOpaque(false);
        jPanel_showTiming.setLayout(new javax.swing.BoxLayout(jPanel_showTiming, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(jPanel_showTiming);
        jPanel_showTiming.setBounds(80, 240, 690, 470);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/spi-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 870, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackhomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
      new DNewhome(email).setVisible(true);
    }//GEN-LAST:event_jBackhomeActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
      new A_Home().setVisible(true);
    }//GEN-LAST:event_jLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_shows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_shows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_shows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_shows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_shows().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackhome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_showTiming;
    private javax.swing.JButton jLogout;
    private javax.swing.JPanel jPanel_showTiming;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void show(JInternalFrame muv1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    class Action implements ActionListener {  
      
      int id;
      Action(int i){
          id = i;
      }
      
      public void actionPerformed (ActionEvent e) {     
          new G_theatre(id,movie_id,date,ticket_count,movie_name,email).setVisible(true);
          F_shows.this.setVisible(false);
      }
    }   
    class Action1 implements ActionListener {  
      
      String time;
      int theatre_id,timing_id;     
      Action1(String t,int tid, int time_id){
          time=t;
          theatre_id=tid;   
          timing_id=time_id;
          
      }
      
      public void actionPerformed (ActionEvent e) { 
          new H_confirm(movie_name,movie_id,date,time,ticket_count,theatre_id,timing_id,email).setVisible(true);
          F_shows.this.setVisible(false);
      }
    } 
}
