/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.ticket;

import java.awt.Image;
import javax.swing.*;
import javax.imageio.ImageIO;
import java.util.Date;
import java.sql.*;

/**
 *
 * @author User
 */
public class G_theatre extends javax.swing.JFrame {
int Tid,Mid,tc; 
String name,address,mobile,image,mname,email;
Image img;
Date date;
    /**
     * Creates new form DNewhome
     */
    public G_theatre() {
        
        initComponents();
    }
    
   
    public G_theatre(int id,int mid,Date d, int tc,String moviename,String mail) {
         Tid=id;
         Mid=mid;
         this.tc=tc;
         date=d;
         mname=moviename;
         email=mail;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel_cinema = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        //Class.forName("java.sql.DriverManager");
        Connection con=null;
        /*Statement stmt= (Statement) con.createStatement();
        String query="Select name,address,mobile from theatre where theatreid='"+Tid+"';";
        ResultSet rs= (ResultSet) stmt.executeQuery(query);
        if(rs.next()){
            name=rs.getString("Name");
            address=rs.getString("address");
            mobile=rs.getString("mobile");
        }*/

        CallableStatement cs;
        String columnValue="";
        String name = "nill";
        String addr = "nill";
        String image = "nill";
        String mobile_no = "0";
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
            cs = con.prepareCall("{CALL getTheatre_pro(?)}");
            cs.setInt(1,Tid);
            ResultSet rs = cs.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnsNumber = rsmd.getColumnCount();

            while (rs.next()) {
                for (int i = 1; i <= columnsNumber; i++) {
                    if (i > 1)
                    System.out.print(",  ");
                    columnValue = rs.getString(i);
                    System.out.print(columnValue);
                }
                System.out.println("");
            }
            if(columnValue != "null"){
                String[] values = columnValue.split(";");
                name= values[0];
                addr= values[1];
                mobile_no= values[2];
                image= values[4];
                System.out.println(name+" "+addr+" "+mobile_no+" "+img+"\n");
                img = ImageIO.read(getClass().getResource("/pictures"+image));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jLabel_TheatreAddress = new javax.swing.JLabel();
        jLabel_TheatreContact = new javax.swing.JLabel();
        jLabel_TheatreName = new javax.swing.JLabel();
        jTheatreImg = new javax.swing.JLabel();
        jTheatreImg.setIcon(new ImageIcon(img));
        jLogout = new javax.swing.JButton();
        jLabel_logo = new javax.swing.JLabel();
        jBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 20, 860, 800));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(860, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(860, 800));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 150, 860, 2);

        jLabel_cinema.setFont(new java.awt.Font("Lithos Pro Regular", 0, 24)); // NOI18N
        jLabel_cinema.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cinema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cinema.setText("Cinema");
        getContentPane().add(jLabel_cinema);
        jLabel_cinema.setBounds(370, 180, 118, 32);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setOpaque(false);

        jLabel_TheatreAddress.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        jLabel_TheatreAddress.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TheatreAddress.setText(addr);

        jLabel_TheatreContact.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        jLabel_TheatreContact.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TheatreContact.setText("Contact : 0"+mobile_no);

        jLabel_TheatreName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel_TheatreName.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_TheatreName.setText(name);

        jTheatreImg.setForeground(new java.awt.Color(204, 204, 204));
        jTheatreImg.setText("<User Code>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTheatreImg, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_TheatreContact)
                            .addComponent(jLabel_TheatreAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel_TheatreName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel_TheatreName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_TheatreAddress)
                .addGap(18, 18, 18)
                .addComponent(jLabel_TheatreContact)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTheatreImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(60, 280, 740, 166);

        jLogout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(240, 240, 240));
        jLogout.setText("Log Out");
        jLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLogout.setBorderPainted(false);
        jLogout.setContentAreaFilled(false);
        jLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jLogout);
        jLogout.setBounds(770, 0, 90, 34);

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/logo-edit.png"))); // NOI18N
        getContentPane().add(jLabel_logo);
        jLabel_logo.setBounds(80, 0, 180, 150);

        jBack.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBack.setForeground(new java.awt.Color(240, 240, 240));
        jBack.setText("Back");
        jBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        jBack.setContentAreaFilled(false);
        jBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBack);
        jBack.setBounds(710, 470, 90, 34);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/spi-bg.jpg"))); // NOI18N
        jLabel11.setAlignmentY(0.0F);
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -50, 860, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
         new A_Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new F_shows(date,tc,Mid,mname,email).setVisible(true);
    }//GEN-LAST:event_jBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G_theatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G_theatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G_theatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G_theatre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new G_theatre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBack;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel_TheatreAddress;
    private javax.swing.JLabel jLabel_TheatreContact;
    private javax.swing.JLabel jLabel_TheatreName;
    private javax.swing.JLabel jLabel_cinema;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JButton jLogout;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jTheatreImg;
    // End of variables declaration//GEN-END:variables
}
