/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.ticket;

import java.util.ArrayList;
import java.util.Date;
import java.util.Timer;
import javax.swing.JOptionPane;
import java.util.TimerTask;

/**
 *
 * @author Koushi
 */
public class J_Payment extends javax.swing.JFrame {

    int a, totalcost, timing_id, ticket_count;
    String email;
    Date date;
    ArrayList<String> seatnames = new ArrayList<String>();

    /**
     * Creates new form V_Payment
     */
    public J_Payment() {
        initComponents();
    }

    public J_Payment(ArrayList seats, int total, int timeid, Date d, String mail, int tc) {
        seatnames = seats;
        totalcost = total;
        timing_id = timeid;
        email = mail;
        date = d;
        ticket_count=tc;
        initComponents();
    }

    class CloseDialogTask extends TimerTask {

        public void run() {
            jFrame1.setVisible(false);
            J_Payment.this.setVisible(false);
            new K_end(seatnames, totalcost, timing_id, email, date,ticket_count).setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jTextField_Cardnumber = new javax.swing.JTextField();
        jPaynow = new javax.swing.JButton();
        jLabel207 = new javax.swing.JLabel();
        jCombo_ExpiryMonth = new javax.swing.JComboBox<>();
        jCombo_ExpiryYear = new javax.swing.JComboBox<>();
        jLabel208 = new javax.swing.JLabel();
        jTextField_cardname = new javax.swing.JTextField();
        jTextField_CVV = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jFrame1.setResizable(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Ecxd.gif"))); // NOI18N
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 20, 860, 800));
        setMinimumSize(new java.awt.Dimension(860, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(860, 800));
        getContentPane().setLayout(null);

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel48.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextField_Cardnumber.setText("CREDIT CARD NUMBER");
        jTextField_Cardnumber.setToolTipText("Enter 16-Digit Card Number.");
        jTextField_Cardnumber.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_Cardnumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_CardnumberMouseClicked(evt);
            }
        });
        jTextField_Cardnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CardnumberActionPerformed(evt);
            }
        });

        jPaynow.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jPaynow.setText("PAY NOW");
        jPaynow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPaynow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPaynowActionPerformed(evt);
            }
        });

        jLabel207.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/cards.png"))); // NOI18N

        jCombo_ExpiryMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expiry Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jCombo_ExpiryMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCombo_ExpiryYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expiry Year", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));
        jCombo_ExpiryYear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCombo_ExpiryYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_ExpiryYearActionPerformed(evt);
            }
        });

        jLabel208.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/CVV.png"))); // NOI18N

        jTextField_cardname.setText("NAME ON CARD");
        jTextField_cardname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_cardname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_cardnameMouseClicked(evt);
            }
        });
        jTextField_cardname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cardnameActionPerformed(evt);
            }
        });

        jTextField_CVV.setText("CVV");
        jTextField_CVV.setToolTipText("What is CVV?\n The last three digits given on back of your card.");
        jTextField_CVV.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_CVV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_CVVMouseClicked(evt);
            }
        });
        jTextField_CVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CVVActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel29.setText("Payment  : ");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Total Amount : ");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Rs."+totalcost);

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel48Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel48Layout.createSequentialGroup()
                        .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel48Layout.createSequentialGroup()
                                .addComponent(jTextField_Cardnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel207, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel29)
                            .addGroup(jPanel48Layout.createSequentialGroup()
                                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_cardname, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel48Layout.createSequentialGroup()
                                        .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_CVV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCombo_ExpiryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel48Layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jCombo_ExpiryYear, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel48Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel208, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(105, 105, 105)
                                .addComponent(jPaynow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(35, Short.MAX_VALUE))))
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addGap(29, 29, 29)
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Cardnumber)
                    .addComponent(jLabel207, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCombo_ExpiryYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jCombo_ExpiryMonth, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel48Layout.createSequentialGroup()
                        .addGroup(jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_CVV)
                            .addComponent(jLabel208, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_cardname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPaynow, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel48);
        jPanel48.setBounds(180, 260, 494, 330);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 150, 860, 10);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/logo-edit.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 0, 190, 150);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Cancel");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 700, 90, 34);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/spi-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 860, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_CardnumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_CardnumberMouseClicked
        jTextField_Cardnumber.setText("");        
    }//GEN-LAST:event_jTextField_CardnumberMouseClicked

    private void jPaynowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPaynowActionPerformed
        // TODO add your handling code here:
        String msg = "Please enter Valid";
        int cardnum_length = jTextField_Cardnumber.getDocument().getLength();
        int cvv = jTextField_CVV.getDocument().getLength();
        int flag = 0;
        if (jTextField_Cardnumber.getText() == "CREDIT CARD NUMBER" || jTextField_Cardnumber.getText() == "" || jCombo_ExpiryMonth.getSelectedItem().toString() == "Expiry Month"
                || jCombo_ExpiryYear.getSelectedItem() == "Expiry Year" || jTextField_CVV.getText() == "CVV" || jTextField_CVV.getText() == ""
                || jTextField_cardname.getText() == "" || jTextField_cardname.getText() == "NAME ON CARD") {

            JOptionPane.showMessageDialog(this, "Please Enter all the Details");
        }
        if (cardnum_length != 16) {
            flag = 1;
            msg = msg + " Card Number";
        }

        if (cvv != 3) {
            flag = 1;
            msg = msg + " CVV";
        }
        if (cardnum_length == 16 && cvv == 3 && jCombo_ExpiryMonth.getSelectedIndex() != 0 && jCombo_ExpiryYear.getSelectedIndex() != 0) {
            String cardnum = jTextField_Cardnumber.getText();
            String cvvnum = jTextField_CVV.getText();
            int i, j;
            for (i = 0; i <= 15; i++) {
                if (cardnum.charAt(i) < '0' || cardnum.charAt(i) > '9') {
                    JOptionPane.showMessageDialog(this, "Enter valid details.");
                    break;
                }
            }
            for (j = 0; j <= 2; j++) {
                if (cvvnum.charAt(j) < '0' || cvvnum.charAt(j) > '9') {
                    JOptionPane.showMessageDialog(this, "Enter valid details.");
                    break;
                }
            }
            if (i == 16 && j == 3) {
                jFrame1.setVisible(true);
                jFrame1.setLocationRelativeTo(this);                
                jFrame1.pack();

                int timeout_ms = 4000;
                Timer timer = new Timer();
                timer.schedule(new J_Payment.CloseDialogTask(), timeout_ms);
            }
        }
        if (flag == 1) {
            JOptionPane.showMessageDialog(this, msg);
        }

    }//GEN-LAST:event_jPaynowActionPerformed

    private void jTextField_cardnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_cardnameMouseClicked
        // TODO add your handling code here:
        jTextField_cardname.setText("");
    }//GEN-LAST:event_jTextField_cardnameMouseClicked

    private void jTextField_cardnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cardnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cardnameActionPerformed

    private void jTextField_CVVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_CVVMouseClicked
        jTextField_CVV.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CVVMouseClicked

    private void jTextField_CVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CVVActionPerformed

    private void jTextField_CardnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CardnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CardnumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DNewhome(email).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCombo_ExpiryYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_ExpiryYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombo_ExpiryYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(J_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(J_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(J_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(J_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new J_Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCombo_ExpiryMonth;
    private javax.swing.JComboBox<String> jCombo_ExpiryYear;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    public static javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JButton jPaynow;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_CVV;
    private javax.swing.JTextField jTextField_Cardnumber;
    private javax.swing.JTextField jTextField_cardname;
    // End of variables declaration//GEN-END:variables
}
