/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.ticket;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class K_end extends javax.swing.JFrame {

    int totalcost, timing_id, ticket_count;
    String email, Date;
    Date date;
    ArrayList<String> seatnames = new ArrayList<String>();

    /**
     * Creates new form W_end
     */
    public K_end() {
        initComponents();
    }

    public K_end(ArrayList seat, int total, int timingid, String mail, Date d, int tc) {
        seatnames = seat;
        date = d;
        DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
        Date = df.format(d);
        totalcost = total;
        email = mail;
        timing_id = timingid;
        ticket_count = tc;
        Connection con = null;
        System.out.println(timing_id+" "+seatnames+" "+email+" "+Date+" " );
        java.sql.Date sqldate = new java.sql.Date(date.getTime());
        CallableStatement cs, cs1;
        String sn;

        try {
            /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
            for (int i = 0; i < seatnames.size(); i++) {
                cs = con.prepareCall("{CALL insSeats(?,?,?,?)}");
                sn = seatnames.get(i);
                cs.setInt(1, timing_id);
                cs.setString(2, sn);
                cs.setString(3, email);
                cs.setDate(4,sqldate);
                ResultSet rs = cs.executeQuery();
            }*/

            Class.forName("java.sql.DriverManager");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
            for (int i = 0; i < seatnames.size(); i++) {
                Statement stmt = (Statement) con.createStatement();
                String query = "Insert into seat(timingid,seatname,email,date) values('" + timing_id + "','" + seatnames.get(i) + "','" + email + "','" + Date + "');";
                stmt.executeUpdate(query);
            }/*
            Statement stmt2 = (Statement) con.createStatement();
            String query2 = "Update timing set no_of_seatsBooked=no_of_seatsBooked+'" + ticket_count + "' where timingid = '" + timing_id + "';";
            stmt2.executeUpdate(query2);*/
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/package?characterEncoding=latin1", "root", "snehAA2632000");
            cs1 = con.prepareCall("{CALL updTiming(?,?)}");
            cs1.setInt(1, timing_id);
            cs1.setInt(2,ticket_count); 
            ResultSet rs = cs1.executeQuery();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jBookmore = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 20, 860, 800));
        setMinimumSize(new java.awt.Dimension(860, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(860, 800));
        getContentPane().setLayout(null);

        jLabel28.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Thank You For Using Cinepop !!!");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel28);
        jLabel28.setBounds(0, 520, 860, 60);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("Seats Booked :");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(170, 350, 150, 26);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("Total Amount :");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(170, 300, 130, 26);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/CheckedMark._FMpng_SX50_.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(200, 160, 50, 128);

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(240, 240, 240));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Your seats have been booked succcessfully.");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(280, 160, 470, 128);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 157, 860, 10);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setText("Rs."+totalcost);
        getContentPane().add(jLabel24);
        jLabel24.setBounds(310, 300, 120, 26);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jLabel26.setText(Arrays.toString(seatnames.toArray()).replace("[", "").replace("]", ""));
        getContentPane().add(jLabel26);
        jLabel26.setBounds(310, 350, 400, 26);

        jBookmore.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jBookmore.setText("Book More Tickets");
        jBookmore.setToolTipText("Click here to book more tickets");
        jBookmore.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBookmore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBookmore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBookmoreActionPerformed(evt);
            }
        });
        getContentPane().add(jBookmore);
        jBookmore.setBounds(280, 430, 151, 34);

        jExit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jExit.setText("Exit");
        jExit.setToolTipText("Finished booking ? Click here to logout and close application");
        jExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit);
        jExit.setBounds(480, 430, 68, 34);

        jLogout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLogout.setForeground(new java.awt.Color(240, 240, 240));
        jLogout.setText("Log Out");
        jLogout.setBorderPainted(false);
        jLogout.setContentAreaFilled(false);
        jLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jLogout);
        jLogout.setBounds(775, 0, 90, 34);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/logo-edit.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 0, 200, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/spi-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 870, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBookmoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBookmoreActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DNewhome(email).setVisible(true);
    }//GEN-LAST:event_jBookmoreActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BLogin().setVisible(true);
    }//GEN-LAST:event_jLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(K_end.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(K_end.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(K_end.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(K_end.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new K_end().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBookmore;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    public static javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JButton jLogout;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
